### ISSUE TITLE
Misleading error message for have_a_valid_cert failure

### ISSUE THREAD

**Issue by dogweather** [dogweather/rspec-webservice_matchers#25]
When the location returns a redirect, we seem to get this:

<img width="600" alt="screen shot 2016-02-13 at 12 39 30 am" src="https://cloud.githubusercontent.com/assets/150670/13026814/7e0caad6-d1ea-11e5-864e-16fb61dde7cd.png">

The expectation was,

```ruby
expect('bloc.io').to have_a_valid_cert
```

I'm not sure what the correct output should be in the case of a redirect. We could either first follow the redirects and then do the SSL test. Or, we could strictly test the given domain/url and thus fail.

**Edit:** We decided to keep this matcher simple and improve the error message. Meanwhile, we'll work on `after_following_redirects` for chaining.

**Comment by supremebeing7** [comment]
Seems like you'd want to keep both options. Wonder if there would be a simple way to have chainable expectations? So you could allow `have_a_valid_cert` to keep it's current behavior, then allow chaining an additional piece on - i.e. `after_following_redirects`. So a passing spec would be 

    expect('bloc.io').to have_a_valid_cert.after_following_redirects

Thoughts?

I've never done any custom matcher stuff before, but if I have time I'd be willing to try to implement this if it seems sensible.

**Comment by dogweather** [comment]
I like that idea. I haven't tried chaining yet with these, but this'll be very interesting.

**Comment by dogweather** [comment]
Seems to be due to an Excon bug, and created this issue:
https://github.com/excon/excon/issues/546

**Comment by dogweather** [comment]
Fixed in gem version 4.1.3.
